### ISSUE TITLE
Update details page before release

### ISSUE THREAD

**Issue by smmatte** [microsoft/vscode-python-devicesimulator#149]

**Comment by DonJayamanne** [comment]
The PR adds a link to the repo, along with some additional useful information https://github.com/microsoft/vscode-python-devicesimulator/pull/159

**Comment by vandyliu** [comment]
I'll be closing this issue for now as the original description disappeared and there doesn't seem like there needs to be more work done. Hope that's okay @markAtMicrosoft

Can reopen if necessary.
