### ISSUE TITLE
Include repo in package.json for issues

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-python-devicesimulator#156]
You should link to this repo in the package.json to make it easier for people to file issues or submit PRs:

```
  "repository": {
    "type": "git",
    "url": "https://github.com/microsoft/vscode-python-devicesimulator.git"
  },
  "bugs": {
    "url": "https://github.com/microsoft/vscode-python-devicesimulator/issues"
  },
```

**Comment by DonJayamanne** [comment]
Landed a PR to resolve this https://github.com/microsoft/vscode-python-devicesimulator/pull/159

**Comment by roblourens** [comment]
Thanks! I would have sent a PR but I was on a very bad connection at the time...

**Comment by vandyliu** [comment]
Issue fixed in [PR159](https://github.com/microsoft/vscode-python-devicesimulator/pull/159). Marking it as closed, let us know if you encounter any other issue.
