### ISSUE TITLE
Extension logs noisily

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-python-devicesimulator#158]
- Install and run the extension
- Open developer tools (Help > Toggle Developer Tools)
- See pages of log messages:

![image](https://user-images.githubusercontent.com/323878/68532715-f1c65380-02ee-11ea-8b6b-0f3f655c8826.png)

- Please only log if necessary. You can also respect vscode's log level or add a setting if you want to enable logging. Or you could log to an update channel (but still be careful about producing very large files)

**Comment by LukeSlev** [comment]
Hey @roblourens, looking at those logs it looks like those are actually coming from the Python extension which our extension depends on. As a result we don't have too much control over the level of logging that they do. However, you could always post an issue on the Python repo! https://github.com/microsoft/vscode-python

**Comment by DonJayamanne** [comment]
Agreed, its our Python extension that's logging this info. Can be closed in favor of https://github.com/microsoft/vscode-python/issues/2156

**Comment by roblourens** [comment]
Sorry, I didn't look closely
