### ISSUE TITLE
What are the style guidelines?

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-python-devicesimulator#161]
When submitting a PR, there's a section about following style guidelines. However I coudln't find any!

`- [ ] My code follows the style guidelines of this project`

**Comment by iennae** [comment]
We'll work on putting that together. Thank you!

**Comment by gramster** [comment]
I added a CODING_STANDARDS.md. Not sure if the code here actually adheres to these standards itself but I think they are what we should be doing, so consider them aspirational for now.
