### ISSUE TITLE
Deal with security alerts

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode-python-devicesimulator#171]
There are already two PRs to bump the appropriate version to dismiss them.

https://github.com/microsoft/vscode-python-devicesimulator/network/alerts

**Comment by vandyliu** [comment]
Merged in [165](https://github.com/microsoft/vscode-python-devicesimulator/pull/165) and [164](https://github.com/microsoft/vscode-python-devicesimulator/pull/164).

We'll be faster to merge the dependency PRs next time.
