### ISSUE TITLE
Dropdown on simulator displays wrong file sometimes

### ISSUE THREAD

**Issue by vandyliu** [microsoft/vscode-python-devicesimulator#226]
Steps to reproduce:
1. Run microbit_file1.py on microbit simulator.
2. Go to microbit_file2.py and save it.
3. Notice on the simulator, it now says it is `currently running mirocbit_file2.py` when it is running microbit_file1.py

**Comment by xnkevinnguyen** [comment]
It is currently showing the focused file. We plan to remove the dropdown and have "Currently selected file" (This is the file that would run when clicking run simulator)

**Comment by vandyliu** [comment]
Fixed in #263
