### ISSUE TITLE
On debug mode CLUE, terminal screen is not properly printed

### ISSUE THREAD

**Issue by xnkevinnguyen** [microsoft/vscode-python-devicesimulator#347]
Currently on debug mode, the terminal screen is not showing as it is not communicated with socket IO like other images.

Repro code to run on debug mode: 
```
# import CPX library
from adafruit_circuitplayground import cp

print("hello world")

```
current: No display is shown
expected: Display terminal with print statements

**Comment by andreamah** [comment]
Fixed in #351
