### ISSUE TITLE
Toolbar tool tips have inconsistencies 

### ISSUE THREAD

**Issue by vandyliu** [microsoft/vscode-python-devicesimulator#354]
This is most notable for the micro:bit simulator.
1. Some icons have two tooltips (one bigger and one smaller) and some only have one. We should probably just have one. 
2. Sometimes when there are two tooltips, they have contradicting titles.
3. Temperature sensor and light sensor tooltips are typed like constant names instead of titles.
![Code_qPjKEvIvMm](https://user-images.githubusercontent.com/33995460/79912222-896bba00-83d6-11ea-813e-1008c79fa967.png)
![Code_jFw1gCExdS](https://user-images.githubusercontent.com/33995460/79912225-8a045080-83d6-11ea-8aad-a62f4b6f43db.png)

**Comment by xnkevinnguyen** [comment]
Closed with this PR #359
