### ISSUE TITLE
Text/input boxes for simulating sensor data should be improved

### ISSUE THREAD

**Issue by vandyliu** [microsoft/vscode-python-devicesimulator#356]
![Code_H4M9CCLZMs](https://user-images.githubusercontent.com/33995460/79912611-229ad080-83d7-11ea-9a21-c893a5b1095e.png)
The value in the box is -1000.4
We should adjust the styles of the box so that the whole number fits in the box nicely.
This is in the accelerometer sensor section for the CLUE.

**Comment by eishan05** [comment]
Do you mean dynamically adjust the width, or give the box enough width to begin with?
