### ISSUE TITLE
Getting started tab for Circuit Playground Express references micro:bit

### ISSUE THREAD

**Issue by kattni** [microsoft/vscode-python-devicesimulator#367]
The first instruction on the Getting started tab for the Circuit Playground Express is "Import the micro:bit library to use it (This is required)". 

Presumably it should say "Import the Circuit Playground library to use it (This is required)"

![GettingStartedCPX](https://user-images.githubusercontent.com/7865090/81221604-12771980-8fb1-11ea-803d-6a296d1bedcd.png)

**Comment by xnkevinnguyen** [comment]
Fixed with #370
