### ISSUE TITLE
Editor toolbar buttons show on all Python files

### ISSUE THREAD

**Issue by int19h** [microsoft/vscode-python-devicesimulator#79]
The buttons for Open/Run/Deploy to Simulator show in all .py editors once the extension is installed. Since they're not relevant to code that is not intended to run on the simulator, there needs to be some way to only bring them up in the relevant context.

**Comment by andreamah** [comment]
Hi @int19h ,

Sorry for the late follow-up! After some consideration of this issue, we decided to remove the top toolbar in the extension's recent releases. As for taking the design of the VSCode AL/ML into consideration for improving the toolbar, it is currently on our backlog. 
 
Thanks for the suggestions! 😀

**Comment by xnkevinnguyen** [comment]
The editor toolbar buttons have been removed from the extension.
